# Generated by Django 4.2.30 on 2026-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('tenis', 'Tenis'), ('baloncesto', 'Baloncesto'), ('volleyball', 'Volleyball')], default='futbol', max_length=20),
        ),
    ]
